server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}

app:
  storage-root: ${APP_STORAGE_ROOT:G:/arc_Y_disc}
  metadata-cache-dir: ${APP_METADATA_CACHE_DIR:G:/arc_Y_disc/.metadata_cache}
  thumbnail-cache-dir: ${APP_THUMBNAIL_CACHE_DIR:G:/arc_Y_disc/.thumbnails}
  preview-cache-dir: ${APP_PREVIEW_CACHE_DIR:G:/arc_Y_disc/.previews}

  ffmpeg-path: ${APP_FFMPEG_PATH:ffmpeg}
  ffprobe-path: ${APP_FFPROBE_PATH:ffprobe}
  magick-path: ${APP_MAGICK_PATH:magick}

  security:
    username: ${APP_SECURITY_USERNAME:admin}
    password: ${APP_SECURITY_PASSWORD:12345}

logging:
  level:
    org.apache.catalina: ERROR
    org.apache.coyote: ERROR
    org.springframework.web.context.request.async: ERROR

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

## application.yml
##
## Здесь лежит конфигурация приложения.
## Spring Boot автоматически читает этот файл при запуске.
#
#server:
#  # Порт встроенного сервера.
#  # То есть приложение будет открываться по адресу:
#  # http://localhost:8080
#  address: ${SERVER_ADDRESS:0.0.0.0}
#  port: ${SERVER_PORT:8080}
#
#app:
#  storage-root: ${APP_STORAGE_ROOT:G:/arc_Y_disc}
#  # Корневая папка на диске, которую мы открываем в веб-интерфейсе.
#  # Все операции будут разрешены только внутри этой папки.
#  metadata-cache-dir: ${APP_METADATA_CACHE_DIR:G:/arc_Y_disc/.metadata_cache}
#
##  metadata-cache-dir: G:/arc_Y_disc/.metadata_cache
#
#  thumbnail-cache-dir: ${APP_THUMBNAIL_CACHE_DIR:G:/arc_Y_disc/.thumbnails}
#  preview-cache-dir: ${APP_PREVIEW_CACHE_DIR:G:/arc_Y_disc/.previews}
##  storage-root: G:/arc_Y_disc
#
##  magick-path: magick
##  ffprobe-path: ffprobe
#  magick-path: ${APP_MAGICK_PATH:magick}
#  ffprobe-path: ${APP_FFPROBE_PATH:ffprobe}
#  ffmpeg-path: ${APP_FFMPEG_PATH:ffmpeg}
#  # Путь к ffmpeg.
#  # Если ffmpeg добавлен в PATH системы,
#  # можно просто оставить "ffmpeg".
##  ffmpeg-path: ffmpeg
#
#  security:
#    # Логин для входа в приложение
##    username: admin
#    username: ${APP_SECURITY_USERNAME:admin}
#    password: ${APP_SECURITY_PASSWORD:12345}
#
#    # Пароль для входа в приложение
##    password: 12345
#logging:
#  level:
#    org.apache.catalina: ERROR
#    org.apache.coyote: ERROR
#    org.springframework.web.context.request.async: ERROR
#spring:
#  servlet:
#    multipart:
#      # Максимальный размер одного файла при загрузке
#      max-file-size: 500MB
#
#      # Максимальный суммарный размер HTTP-запроса,
#      # если загружается несколько файлов сразу
#      max-request-size: 500MB