server:
#  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}

app:
  upload-temp-dir: ${APP_UPLOAD_TEMP_DIR:G:/arc_Y_disc/.upload_tmp}
  storage-root: ${APP_STORAGE_ROOT:G:/arc_Y_disc}
  metadata-cache-dir: ${APP_METADATA_CACHE_DIR:G:/arc_Y_disc/.metadata_cache}
  thumbnail-cache-dir: ${APP_THUMBNAIL_CACHE_DIR:G:/arc_Y_disc/.thumbnails}
  preview-cache-dir: ${APP_PREVIEW_CACHE_DIR:G:/arc_Y_disc/.previews}
  folder-cache-dir: ${APP_FOLDER_CACHE_DIR:G:/arc_Y_disc/.folder_cache}
  ffmpeg-path: ${APP_FFMPEG_PATH:ffmpeg}
  ffprobe-path: ${APP_FFPROBE_PATH:ffprobe}
  magick-path: ${APP_MAGICK_PATH:magick}

  security:
    username: ${APP_SECURITY_USERNAME:admin@amg.com}
    password: ${APP_SECURITY_PASSWORD:$*Uw-sU6xa8Ds5fwM2}

logging:
  level:
    org.apache.catalina: ERROR
    org.apache.coyote: ERROR
    org.springframework.web.context.request.async: ERROR

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB